// Chaque équipe produit UNE ressource unique — crée l'interdépendance en Phase 3
module.exports = [
  {
    id: 'batisseurs',
    name: 'Bâtisseurs',
    emoji: '🏗️',
    color: '#ff6b35',
    tagline: 'La force du village',
    resource: { id: 'bois', label: 'Bois', emoji: '🪵' },
    advantage:    'Construisent 2× plus vite',
    disadvantage: 'Consomment 2× plus de nourriture',
  },
  {
    id: 'explorateurs',
    name: 'Explorateurs',
    emoji: '🗺️',
    color: '#00b4d8',
    tagline: 'Les yeux de l\'île',
    resource: { id: 'plans', label: 'Plans', emoji: '📐' },
    advantage:    'Trouvent des raccourcis et ressources cachées',
    disadvantage: 'Peu efficaces s\'ils restent au camp',
  },
  {
    id: 'chasseurs',
    name: 'Chasseurs',
    emoji: '🏹',
    color: '#06d6a0',
    tagline: 'Nourrir la tribu',
    resource: { id: 'nourriture', label: 'Nourriture', emoji: '🍖' },
    advantage:    'Assurent la subsistance de tout le groupe',
    disadvantage: 'Mauvais en construction',
  },
  {
    id: 'guerisseurs',
    name: 'Guérisseurs',
    emoji: '⚕️',
    color: '#ffd166',
    tagline: 'La vie du camp',
    resource: { id: 'eau', label: 'Eau', emoji: '💧' },
    advantage:    'Soignent et maintiennent le moral à 100 %',
    disadvantage: 'Ne peuvent pas travailler seuls',
  },
];
